version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
    - echo Installing dependencies...
  build:
    commands:
    - echo Running tests...
  post_build:
      commands:
        - echo Build completed successfully
artifacts:
  files:
    - '**/*'
  base-directory: .
      